# Book settings
title                       : NASA's Transform to Open Science Mission  # The title of the book. Will be placed in the left navbar.
author                      : TOPS Community # The author of the book
copyright                   : "CC-BY"  # Copyright year to be placed in the footer
logo                        : https://github.com/nasa/Transform-to-Open-Science/blob/main/docs/Area1_Engagement/branding_graphics/Tops_Badge_Nasa.png
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files        : true

execute:
  execute_notebooks: 'off'
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://nasa.github.io/Transform-to-Open-Science"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  use_repository_button     : true
  use_edit_page_button      : true
  use_issues_button         : true
#  google_analytics_id       : "UA-148221575-1"  # A GA id that can be used to track book views.


repository:
  url                       : https://github.com/nasa/Transform-to-Open-Science  # The URL to your book's repository
  branch                    : main  # Which branch of the repository should be used when creating links

sphinx:
  config:
    exclude_patterns:
      - README.md
    myst_enable_extensions: 
    - amsmath
    - dollarmath
    - html_image
    - html_admonition
    - tasklist
